# Generated by Django 4.0 on 2022-10-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='country_arrival',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='country_departure',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
